export interface VehicleModelSuggestion {
  brand: string;
  model: string;
}

export const INDIAN_VEHICLE_DATABASE: VehicleModelSuggestion[] = [
  // Hero MotoCorp
  { brand: 'Hero', model: 'Splendor Plus' },
  { brand: 'Hero', model: 'Splendor XTEC' },
  { brand: 'Hero', model: 'HF Deluxe' },
  { brand: 'Hero', model: 'Passion Plus' },
  { brand: 'Hero', model: 'Passion Pro' },
  { brand: 'Hero', model: 'Glamour' },
  { brand: 'Hero', model: 'Glamour XTEC' },
  { brand: 'Hero', model: 'Super Splendor' },
  { brand: 'Hero', model: 'Xtreme 125R' },
  { brand: 'Hero', model: 'Xtreme 160R' },
  { brand: 'Hero', model: 'Xtreme 200S' },
  { brand: 'Hero', model: 'XPulse 200 4V' },
  { brand: 'Hero', model: 'XPulse 200T 4V' },
  { brand: 'Hero', model: 'Karizma XMR' },
  { brand: 'Hero', model: 'Mavrick 440' },
  { brand: 'Hero', model: 'Pleasure Plus' },
  { brand: 'Hero', model: 'Maestro Edge 110' },
  { brand: 'Hero', model: 'Maestro Edge 125' },
  { brand: 'Hero', model: 'Xoom 110' },

  // Honda 2-Wheelers
  { brand: 'Honda', model: 'Activa 6G' },
  { brand: 'Honda', model: 'Activa 125' },
  { brand: 'Honda', model: 'Shine 100' },
  { brand: 'Honda', model: 'Shine 125' },
  { brand: 'Honda', model: 'SP 125' },
  { brand: 'Honda', model: 'SP 160' },
  { brand: 'Honda', model: 'Unicorn 160' },
  { brand: 'Honda', model: 'Dio' },
  { brand: 'Honda', model: 'Dio 125' },
  { brand: 'Honda', model: 'Hornet 2.0' },
  { brand: 'Honda', model: 'CB200X' },
  { brand: 'Honda', model: 'CB350' },
  { brand: 'Honda', model: 'CB350RS' },
  { brand: 'Honda', model: 'Hness CB350' },
  { brand: 'Honda', model: 'CB300R' },
  { brand: 'Honda', model: 'CB300F' },
  { brand: 'Honda', model: 'CB500X' },
  { brand: 'Honda', model: 'CBR650R' },
  { brand: 'Honda', model: 'XL750 Transalp' },
  { brand: 'Honda', model: 'Africa Twin' },

  // TVS Motor Company
  { brand: 'TVS', model: 'Jupiter 110' },
  { brand: 'TVS', model: 'Jupiter 125' },
  { brand: 'TVS', model: 'Ntorq 125' },
  { brand: 'TVS', model: 'Apache RTR 160 2V' },
  { brand: 'TVS', model: 'Apache RTR 160 4V' },
  { brand: 'TVS', model: 'Apache RTR 180' },
  { brand: 'TVS', model: 'Apache RTR 200 4V' },
  { brand: 'TVS', model: 'Apache RTR 310' },
  { brand: 'TVS', model: 'Apache RR 310' },
  { brand: 'TVS', model: 'Raider 125' },
  { brand: 'TVS', model: 'Radeon' },
  { brand: 'TVS', model: 'Star City Plus' },
  { brand: 'TVS', model: 'Sport' },
  { brand: 'TVS', model: 'XL 100 Comfort' },
  { brand: 'TVS', model: 'XL 100 Heavy Duty' },
  { brand: 'TVS', model: 'Ronin' },
  { brand: 'TVS', model: 'Zest 110' },
  { brand: 'TVS', model: 'iQube Electric' },
  { brand: 'TVS', model: 'TVS X Electric' },

  // Bajaj Auto
  { brand: 'Bajaj', model: 'Pulsar 125' },
  { brand: 'Bajaj', model: 'Pulsar 150' },
  { brand: 'Bajaj', model: 'Pulsar N150' },
  { brand: 'Bajaj', model: 'Pulsar N160' },
  { brand: 'Bajaj', model: 'Pulsar NS125' },
  { brand: 'Bajaj', model: 'Pulsar NS160' },
  { brand: 'Bajaj', model: 'Pulsar NS200' },
  { brand: 'Bajaj', model: 'Pulsar 220F' },
  { brand: 'Bajaj', model: 'Pulsar N250' },
  { brand: 'Bajaj', model: 'Pulsar F250' },
  { brand: 'Bajaj', model: 'Pulsar NS400Z' },
  { brand: 'Bajaj', model: 'Platina 100' },
  { brand: 'Bajaj', model: 'Platina 110' },
  { brand: 'Bajaj', model: 'CT 110X' },
  { brand: 'Bajaj', model: 'CT 125X' },
  { brand: 'Bajaj', model: 'Avenger Street 160' },
  { brand: 'Bajaj', model: 'Avenger Cruise 220' },
  { brand: 'Bajaj', model: 'Dominar 250' },
  { brand: 'Bajaj', model: 'Dominar 400' },
  { brand: 'Bajaj', model: 'Freedom 125 CNG' },
  { brand: 'Bajaj', model: 'Chetak Electric' },

  // Royal Enfield
  { brand: 'Royal Enfield', model: 'Classic 350' },
  { brand: 'Royal Enfield', model: 'Hunter 350' },
  { brand: 'Royal Enfield', model: 'Bullet 350' },
  { brand: 'Royal Enfield', model: 'Meteor 350' },
  { brand: 'Royal Enfield', model: 'Himalayan 450' },
  { brand: 'Royal Enfield', model: 'Scram 411' },
  { brand: 'Royal Enfield', model: 'Guerrilla 450' },
  { brand: 'Royal Enfield', model: 'Interceptor 650' },
  { brand: 'Royal Enfield', model: 'Continental GT 650' },
  { brand: 'Royal Enfield', model: 'Super Meteor 650' },
  { brand: 'Royal Enfield', model: 'Shotgun 650' },

  // Yamaha
  { brand: 'Yamaha', model: 'FZ-S FI V3' },
  { brand: 'Yamaha', model: 'FZ-S FI V4' },
  { brand: 'Yamaha', model: 'FZ-X' },
  { brand: 'Yamaha', model: 'MT-15 V2' },
  { brand: 'Yamaha', model: 'YZF R15 V4' },
  { brand: 'Yamaha', model: 'YZF R15M' },
  { brand: 'Yamaha', model: 'YZF R3' },
  { brand: 'Yamaha', model: 'MT-03' },
  { brand: 'Yamaha', model: 'RayZR 125 Fi' },
  { brand: 'Yamaha', model: 'Fascino 125 Fi' },
  { brand: 'Yamaha', model: 'Aerox 155' },

  // Suzuki
  { brand: 'Suzuki', model: 'Access 125' },
  { brand: 'Suzuki', model: 'Burgman Street 125' },
  { brand: 'Suzuki', model: 'Avenis 125' },
  { brand: 'Suzuki', model: 'Gixxer 150' },
  { brand: 'Suzuki', model: 'Gixxer SF 150' },
  { brand: 'Suzuki', model: 'Gixxer 250' },
  { brand: 'Suzuki', model: 'Gixxer SF 250' },
  { brand: 'Suzuki', model: 'V-Strom SX' },
  { brand: 'Suzuki', model: 'Hayabusa' },

  // KTM
  { brand: 'KTM', model: 'Duke 125' },
  { brand: 'KTM', model: 'Duke 200' },
  { brand: 'KTM', model: 'Duke 250' },
  { brand: 'KTM', model: 'Duke 390' },
  { brand: 'KTM', model: 'RC 125' },
  { brand: 'KTM', model: 'RC 200' },
  { brand: 'KTM', model: 'RC 390' },
  { brand: 'KTM', model: '250 Adventure' },
  { brand: 'KTM', model: '390 Adventure' },
  { brand: 'KTM', model: '390 Adventure X' },

  // Kawasaki
  { brand: 'Kawasaki', model: 'Ninja 300' },
  { brand: 'Kawasaki', model: 'Ninja 500' },
  { brand: 'Kawasaki', model: 'Ninja 650' },
  { brand: 'Kawasaki', model: 'Ninja ZX-4R' },
  { brand: 'Kawasaki', model: 'Ninja ZX-6R' },
  { brand: 'Kawasaki', model: 'Ninja ZX-10R' },
  { brand: 'Kawasaki', model: 'Z650' },
  { brand: 'Kawasaki', model: 'Z900' },
  { brand: 'Kawasaki', model: 'Versys 650' },
  { brand: 'Kawasaki', model: 'Eliminator' },

  // Triumph
  { brand: 'Triumph', model: 'Speed 400' },
  { brand: 'Triumph', model: 'Scrambler 400X' },
  { brand: 'Triumph', model: 'Trident 660' },
  { brand: 'Triumph', model: 'Tiger Sport 660' },
  { brand: 'Triumph', model: 'Street Triple 765' },
  { brand: 'Triumph', model: 'Bonneville T100' },
  { brand: 'Triumph', model: 'Bonneville Speedmaster' },
  { brand: 'Triumph', model: 'Rocket 3' },

  // Jawa & Yezdi
  { brand: 'Jawa', model: '350' },
  { brand: 'Jawa', model: '42' },
  { brand: 'Jawa', model: '42 Bobber' },
  { brand: 'Jawa', model: 'Peraak' },
  { brand: 'Yezdi', model: 'Roadster' },
  { brand: 'Yezdi', model: 'Scrambler' },
  { brand: 'Yezdi', model: 'Adventure' },

  // Harley-Davidson
  { brand: 'Harley-Davidson', model: 'X440' },
  { brand: 'Harley-Davidson', model: 'Nightster' },
  { brand: 'Harley-Davidson', model: 'Sportster S' },
  { brand: 'Harley-Davidson', model: 'Fat Boy' },
  { brand: 'Harley-Davidson', model: 'Pan America 1250' },

  // BMW Motorrad
  { brand: 'BMW', model: 'G 310 R' },
  { brand: 'BMW', model: 'G 310 GS' },
  { brand: 'BMW', model: 'G 310 RR' },
  { brand: 'BMW', model: 'CE 02 Electric' },
  { brand: 'BMW', model: 'CE 04 Electric' },
  { brand: 'BMW', model: 'F 900 XR' },
  { brand: 'BMW', model: 'R 1250 GS' },
  { brand: 'BMW', model: 'R 1300 GS' },
  { brand: 'BMW', model: 'S 1000 RR' },

  // Ducati
  { brand: 'Ducati', model: 'Scrambler Icon' },
  { brand: 'Ducati', model: 'Monster' },
  { brand: 'Ducati', model: 'Hypermotard 698' },
  { brand: 'Ducati', model: 'Panigale V2' },
  { brand: 'Ducati', model: 'Panigale V4' },
  { brand: 'Ducati', model: 'Multistrada V4' },

  // Aprilia
  { brand: 'Aprilia', model: 'SR 125' },
  { brand: 'Aprilia', model: 'SR 160' },
  { brand: 'Aprilia', model: 'SXR 160' },
  { brand: 'Aprilia', model: 'RS 457' },
  { brand: 'Aprilia', model: 'Tuono 660' },
  { brand: 'Aprilia', model: 'RS 660' },

  // Benelli & Keeway & Moto Morini & CFMoto & BSA
  { brand: 'Benelli', model: 'Imperiale 400' },
  { brand: 'Benelli', model: 'TRK 502' },
  { brand: 'Benelli', model: 'TRK 502X' },
  { brand: 'Keeway', model: 'K-Light 250V' },
  { brand: 'Keeway', model: 'Sixties 300i' },
  { brand: 'Moto Morini', model: 'Seiemmezzo 650' },
  { brand: 'Moto Morini', model: 'X-Cape 650' },
  { brand: 'CFMoto', model: '300NK' },
  { brand: 'BSA', model: 'Gold Star 650' },

  // Indian EV Brands
  { brand: 'Ather', model: '450X' },
  { brand: 'Ather', model: '450S' },
  { brand: 'Ather', model: 'Apex 450' },
  { brand: 'Ather', model: 'Rizta' },
  { brand: 'Ola', model: 'S1 Pro Gen 2' },
  { brand: 'Ola', model: 'S1 Air' },
  { brand: 'Ola', model: 'S1 X 2kWh' },
  { brand: 'Ola', model: 'S1 X 3kWh' },
  { brand: 'Ola', model: 'S1 X 4kWh' },
  { brand: 'Ola', model: 'Roadster Pro' },
  { brand: 'Vida', model: 'V1 Plus' },
  { brand: 'Vida', model: 'V1 Pro' },
  { brand: 'Revolt', model: 'RV400' },
  { brand: 'Revolt', model: 'RV400 BRZ' },
  { brand: 'Ultraviolette', model: 'F77 Mach 2' },
  { brand: 'Ultraviolette', model: 'F77 Space Edition' },
  { brand: 'River', model: 'Indie' },
  { brand: 'Oben', model: 'Rorr' },
  { brand: 'Ampere', model: 'Nexus' },
  { brand: 'Ampere', model: 'Primus' },
  { brand: 'Komaki', model: 'Ranger' },
  { brand: 'Komaki', model: 'SE' },
  { brand: 'Tork', model: 'Kratos R' },
  { brand: 'Hop', model: 'Oxo' },
  { brand: 'Simple Energy', model: 'One' },
  { brand: 'Simple Energy', model: 'Dot One' },
];
